[build]
  command = "npm run build"
  publish = "dist"


## https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file
[[redirects]]
	from = "/manoftheyear"
	to = "/#about"

[[redirects]]
	from = "/*"
	to = "/index.html"
	status = 200

#[[plugins]]
#    package = "@netlify/plugin-lighthouse"
